version: '3.7'

services:
  octoprint:
    restart: always
    image: octoprint/octoprint
    ports:
      - 5000:5000
    devices:
      - /dev/tty1:/dev/tty1
    volumes:
     - octoprint:/home/octoprint

  mjpg-streamer: 
      restart: always
      build: ./mjpg_streamer
      devices:
        - /dev/video0
      ports:
        - 8080:8080

volumes:
  octoprint:
    name: octoprint-mjpg_streamer
